# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np
np.arange(start=2, stop=50, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [2]:
# initilizing list
list1 = [1, 7, 0, 6, 2]
list2 = [4, 2, 5, 8, 9]
 
# converting list to array
arr1 = np.array(list1)
arr2 = np.array(list2)
print(arr1,arr2)

#conatenate two array
arr = np.concatenate((arr1, arr2))

print(arr)

#sort these array
x = np.sort(arr)
print(x)


[1 7 0 6 2] [4 2 5 8 9]
[1 7 0 6 2 4 2 5 8 9]
[0 1 2 2 4 5 6 7 8 9]


# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [3]:
# Creating array object
arr = np.array([[1, 7, 0, 6, 2],
                [4, 2, 5, 8, 9]] )
 
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

No. of dimensions:  2
Size of array:  10


# Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

ANSWER:- We can use np.newaxis and np.expand_dims to increase the dimensions of your existing array.

Using np.newaxis will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
a2 = a[np.newaxis, :]
print(a2.shape)
b = np.expand_dims(a, axis=1)
print(b.shape)

x = np.array([2,5,18,14,4])
y = x[:, np.newaxis]
print(y)

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# column wise conversion of 1D numpy array to 2D Numpy array
arr_2d = np.reshape(arr, (2, 5), order='F')
print('2D Numpy array:')
print(arr_2d)

(6,)
(1, 6)
(6, 1)
[[ 2]
 [ 5]
 [18]
 [14]
 [ 4]]
2D Numpy array:
[[0 2 4 6 8]
 [1 3 5 7 9]]


# Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [5]:
w = np.array([1,2,3])
v = np.array([4,5,6])

print('Horizontal Append:', np.hstack((w, v)))  #Horizontal Append
print('Vertical Append:', np.vstack((w, v))) #Vertical Append

Horizontal Append: [1 2 3 4 5 6]
Vertical Append: [[1 2 3]
 [4 5 6]]


# Questions 6:
How to get unique items and counts of unique items?

In [6]:
import numpy as np

x = np.array([1,1,1,2,2,2,5,25,1,1])
unique, counts = np.unique(x, return_counts=True)

print(np.asarray((unique, counts)).T)
#here first column defined the number present in array and second column defined count(how many times its come)

[[ 1  5]
 [ 2  3]
 [ 5  1]
 [25  1]]


# THANK YOU
